// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTo7ImsyhAvvrpN4Nc5SqWTNKwudAbJNk',
    appId: '1:495226974596:web:f4052bcdff8ed2357aedd1',
    messagingSenderId: '495226974596',
    projectId: 'login-getx-dad01',
    authDomain: 'login-getx-dad01.firebaseapp.com',
    storageBucket: 'login-getx-dad01.firebasestorage.app',
    measurementId: 'G-6C3V7ZE3P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVOuq0fRqErA1KdEPbmUSGGuyQ1CZsfb4',
    appId: '1:495226974596:android:287deb7e11043b627aedd1',
    messagingSenderId: '495226974596',
    projectId: 'login-getx-dad01',
    storageBucket: 'login-getx-dad01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqB1s4ff2qtOM5E_9CghXwV5yUGbkkwM',
    appId: '1:495226974596:ios:4328c42fd82ebda97aedd1',
    messagingSenderId: '495226974596',
    projectId: 'login-getx-dad01',
    storageBucket: 'login-getx-dad01.firebasestorage.app',
    iosBundleId: 'com.faqihasyari.firstGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWqB1s4ff2qtOM5E_9CghXwV5yUGbkkwM',
    appId: '1:495226974596:ios:4328c42fd82ebda97aedd1',
    messagingSenderId: '495226974596',
    projectId: 'login-getx-dad01',
    storageBucket: 'login-getx-dad01.firebasestorage.app',
    iosBundleId: 'com.faqihasyari.firstGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTo7ImsyhAvvrpN4Nc5SqWTNKwudAbJNk',
    appId: '1:495226974596:web:7778dc59501516857aedd1',
    messagingSenderId: '495226974596',
    projectId: 'login-getx-dad01',
    authDomain: 'login-getx-dad01.firebaseapp.com',
    storageBucket: 'login-getx-dad01.firebasestorage.app',
    measurementId: 'G-QXZ9FQP6N9',
  );
}
